export const expansions = [
  {
    label: "Base Game",
    iconUrl: "/Expansion_Base_Game.gif",
  },
  {
    label: "World Adventures",
    iconUrl: "/Expansion_World_Adventures.gif",
  },
  {
    label: "Ambitions",
    iconUrl: "/Expansion_Ambitions.gif",
  },
  {
    label: "Late Night",
    iconUrl: "/Expansion_Late_Night.gif",
  },
  {
    label: "Generations",
    iconUrl: "/Expansion_Generations.gif",
  },
  {
    label: "Pets",
    iconUrl: "/Expansion_Pets.gif",
  },
  {
    label: "Showtime",
    iconUrl: "/Expansion_Showtime.gif",
  },
  {
    label: "Supernatural",
    iconUrl: "/Expansion_Supernatural.gif",
  },
  {
    label: "Seasons",
    iconUrl: "/Expansion_Seasons.gif",
  },
  {
    label: "University Life",
    iconUrl: "/Expansion_University_Life.gif",
  },
  {
    label: "Island Paradise",
    iconUrl: "/Expansion_Island_Paradise.gif",
  },
  {
    label: "Into the Future",
    iconUrl: "/Expansion_Into_the_Future.gif",
  },
];

export const traits = [
  {
    label: "Absent-Minded",
    iconUrl: "/Trait_Absent-Minded.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Absent-Minded", factor: 10 },
      { trait: "Genius", factor: 0.8 },
      { trait: "Artistic", factor: 5 },
    ],
    ownInfluence: [{ trait: "Perceptive", factor: 5 }],
    requiredAge: "baby",
    expansion: "Base Game",
  },
  {
    label: "Artistic",
    iconUrl: "/Trait_Artistic.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Artistic", factor: 10 },
      { trait: "Virtuoso", factor: 5 },
      { trait: "Can't Stand Art", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Can't Stand Art", factor: 0 }],
    requiredAge: "baby",
    expansion: "Base Game",
  },
  {
    label: "Athletic",
    iconUrl: "/Trait_Athletic.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Athletic", factor: 10 },
      { trait: "Adventurous", factor: 5 },
      { trait: "Couch Potato", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Couch Potato", factor: 0 }],
    requiredAge: "baby",
    expansion: "Base Game",
  },
  {
    label: "Brave",
    iconUrl: "/Trait_Brave.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Brave", factor: 10 },
      { trait: "Daredevil", factor: 5 },
      { trait: "Coward", factor: 0.8 },
      { trait: "Loser", factor: 0.8 },
    ],
    ownInfluence: [
      { trait: "Coward", factor: 0 },
      { trait: "Loser", factor: 0 },
    ],
    requiredAge: "baby",
    expansion: "Base Game",
  },
  {
    label: "Clumsy",
    iconUrl: "/Trait_Clumsy.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Clumsy", factor: 10 },
      { trait: "Natural Born Performer", factor: 0.8 },
      { trait: "Handy", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Natural Born Performer", factor: 0 }],
    requiredAge: "baby",
    expansion: "Base Game",
  },
  {
    label: "Couch Potato",
    iconUrl: "/Trait_Couch_Potato.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Couch Potato", factor: 10 },
      { trait: "Athletic", factor: 0.8 },
      { trait: "Technophobe", factor: 0.8 },
      { trait: "Disciplined", factor: 0.8 },
    ],
    ownInfluence: [
      { trait: "Athletic", factor: 0 },
      { trait: "Technophobe", factor: 0 },
      { trait: "Disciplined", factor: 0 },
    ],
    requiredAge: "baby",
    expansion: "Base Game",
  },
  {
    label: "Disciplined",
    iconUrl: "/Trait_Disciplined.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Disciplined", factor: 10 },
      { trait: "Couch Potato", factor: 0.8 },
      { trait: "Rebellious", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Couch Potato", factor: 0 }],
    requiredAge: "baby",
    expansion: "World Adventures",
  },
  {
    label: "Easily Impressed",
    iconUrl: "/Trait_Easily_Impressed.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Easily Impressed", factor: 10 },
      { trait: "Snob", factor: 0.8 },
      { trait: "Can't Stand Art", factor: 0.8 },
      { trait: "Avant Garde", factor: 0.8 },
    ],
    ownInfluence: [
      { trait: "Snob", factor: 0 },
      { trait: "Can't Stand Art", factor: 0 },
      { trait: "Avant Garde", factor: 0 },
    ],
    requiredAge: "baby",
    expansion: "Base Game",
  },
  {
    label: "Eccentric",
    iconUrl: "/Trait_Eccentric.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Eccentric", factor: 10 },
      { trait: "Genius", factor: 5 },
    ],
    ownInfluence: [],
    requiredAge: "baby",
    expansion: "Ambitions",
  },
  {
    label: "Evil",
    iconUrl: "/Trait_Evil.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Evil", factor: 10 },
      { trait: "Good", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Good", factor: 0 }],
    requiredAge: "baby",
    expansion: "Base Game",
  },
  {
    label: "Excitable",
    iconUrl: "/Trait_Excitable.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Excitable", factor: 10 },
      { trait: "Grumpy", factor: 0.8 },
      { trait: "Brooding", factor: 0.8 },
    ],
    ownInfluence: [
      { trait: "Grumpy", factor: 0 },
      { trait: "Brooding", factor: 0 },
    ],
    requiredAge: "baby",
    expansion: "Base Game",
  },
  {
    label: "Friendly",
    iconUrl: "/Trait_Friendly.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Friendly", factor: 10 },
      { trait: "Mean Spirited", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Mean Spirited", factor: 0 }],
    requiredAge: "baby",
    expansion: "Base Game",
  },
  {
    label: "Genius",
    iconUrl: "/Trait_Genius.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Genius", factor: 10 },
      { trait: "Bookworm", factor: 5 },
    ],
    ownInfluence: [],
    requiredAge: "baby",
    expansion: "Base Game",
  },
  {
    label: "Good",
    iconUrl: "/Trait_Good.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Good", factor: 10 },
      { trait: "Friendly", factor: 5 },
    ],
    ownInfluence: [{ trait: "Evil", factor: 0 }, ,],
    requiredAge: "baby",
    expansion: "Base Game",
  },
  {
    label: "Grumpy",
    iconUrl: "/Trait_Grumpy.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Grumpy", factor: 10 },
      { trait: "Hot-Headed", factor: 0.8 },
      { trait: "Excitable", factor: 0.8 },
    ],
    ownInfluence: [
      { trait: "Hot-Headed", factor: 0 },
      { trait: "Excitable", factor: 0 },
    ],
    requiredAge: "baby",
    expansion: "Base Game",
  },
  {
    label: "Hates the Outdoors",
    iconUrl: "/Trait_Hates_the_Outdoors.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Hates the Outdoors", factor: 10 },
      { trait: "Loves the Outdoors", factor: 0.8 },
      { trait: "Eco-Friendly", factor: 0.8 },
      { trait: "Sailor", factor: 0.8 },
    ],
    ownInfluence: [
      { trait: "Loves the Outdoors", factor: 0 },
      { trait: "Eco-Friendly", factor: 0 },
      { trait: "Sailor", factor: 0 },
    ],
    requiredAge: "baby",
    expansion: "Base Game",
  },
  {
    label: "Heavy Sleeper",
    iconUrl: "/Trait_Heavy_Sleeper.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Heavy Sleeper", factor: 10 },
      { trait: "Light Sleeper", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Light Sleeper", factor: 0 }],
    requiredAge: "baby",
    expansion: "Base Game",
  },
  {
    label: "Insane",
    iconUrl: "/Trait_Insane.webp",
    weight: 100,
    parentInfluence: [{ trait: "Insane", factor: 10 }],
    ownInfluence: [],
    requiredAge: "baby",
    expansion: "Base Game",
  },
  {
    label: "Light Sleeper",
    iconUrl: "/Trait_Light_Sleeper.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Light Sleeper", factor: 10 },
      { trait: "Heavy Sleeper", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Heavy Sleeper", factor: 0 }],
    requiredAge: "baby",
    expansion: "Base Game",
  },
  {
    label: "Loner",
    iconUrl: "/Trait_Loner.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Loner", factor: 10 },
      { trait: "Social Butterfly", factor: 0.8 },
      { trait: "Party Animal", factor: 0.8 },
    ],
    ownInfluence: [
      { trait: "Social Butterfly", factor: 0 },
      { trait: "Party Animal", factor: 0 },
    ],
    requiredAge: "baby",
    expansion: "Base Game",
  },
  {
    label: "Loves the Cold",
    iconUrl: "/Trait_Loves_the_Cold.webp",
    weight: 100,
    parentInfluence: [{ trait: "Loves the Cold", factor: 10 }],
    ownInfluence: [],
    requiredAge: "baby",
    expansion: "Seasons",
  },
  {
    label: "Loves the Heat",
    iconUrl: "/Trait_Loves_the_Heat.webp",
    weight: 100,
    parentInfluence: [{ trait: "Loves the Heat", factor: 10 }],
    ownInfluence: [],
    requiredAge: "baby",
    expansion: "Seasons",
  },
  {
    label: "Loves the Outdoors",
    iconUrl: "/Trait_Loves_the_Outdoors.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Loves the Outdoors", factor: 10 },
      { trait: "Angler", factor: 5 },
      { trait: "Hates the Outdoors", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Hates the Outdoors", factor: 0 }],
    requiredAge: "baby",
    expansion: "Base Game",
  },
  {
    label: "Neurotic",
    iconUrl: "/Trait_Neurotic.webp",
    weight: 100,
    parentInfluence: [{ trait: "Neurotic", factor: 10 }],
    ownInfluence: [],
    requiredAge: "baby",
    expansion: "Base Game",
  },
  {
    label: "Perceptive",
    iconUrl: "/Trait_Perceptive.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Perceptive", factor: 10 },
      { trait: "Absent-Minded", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Absent-Minded", factor: 0 }],
    requiredAge: "baby",
    expansion: "Ambitions",
  },
  {
    label: "Sailor",
    iconUrl: "/Trait_Sailor.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Sailor", factor: 10 },
      { trait: "Hydrophobic", factor: 0.8 },
      { trait: "Hates the Outdoors", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Hates the Outdoors", factor: 0 }],
    requiredAge: "baby",
    expansion: "Island Paradise",
  },
  {
    label: "Slob",
    iconUrl: "/Trait_Slob.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Slob", factor: 10 },
      { trait: "Neat", factor: 0.8 },
      { trait: "Proper", factor: 0.8 },
    ],
    ownInfluence: [
      { trait: "Neat", factor: 0 },
      { trait: "Proper", factor: 0 },
    ],
    requiredAge: "baby",
    expansion: "Base Game",
  },
  {
    label: "Virtuoso",
    iconUrl: "/Trait_Virtuoso.webp",
    weight: 100,
    parentInfluence: [{ trait: "Virtuoso", factor: 10 }],
    ownInfluence: [],
    requiredAge: "baby",
    expansion: "Base Game",
  },

  {
    label: "Adventurous",
    iconUrl: "/Trait_Adventurous.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Adventurous", factor: 10 },
      { trait: "Couch Potato", factor: 0.8 },
    ],
    ownInfluence: [],
    requiredAge: "child",
    expansion: "World Adventures",
  },
  {
    label: "Ambitious",
    iconUrl: "/Trait_Ambitious.webp",
    weight: 100,
    parentInfluence: [{ trait: "Ambitious", factor: 10 }, ,],
    ownInfluence: [],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Angler",
    iconUrl: "/Trait_Angler.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Angler", factor: 10 },
      { trait: "Loves the Outdoors", factor: 5 },
    ],
    ownInfluence: [{ trait: "Hates the Outdoors", factor: 0 }],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Animal Lover",
    iconUrl: "/Trait_Animal_Lover.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Animal Lover", factor: 10 },
      { trait: "Equestrian", factor: 5 },
      { trait: "Cat Person", factor: 5 },
      { trait: "Dog Person", factor: 5 },
    ],
    ownInfluence: [
      { trait: "Equestrian", factor: 0 },
      { trait: "Cat Person", factor: 0 },
      { trait: "Dog Person", factor: 0 },
    ],
    requiredAge: "child",
    expansion: "Pets",
  },
  {
    label: "Bookworm",
    iconUrl: "/Trait_Bookworm.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Bookworm", factor: 10 },
      { trait: "Genius", factor: 5 },
    ],
    ownInfluence: [],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Bot Fan",
    iconUrl: "/Trait_Bot_Fan.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Bot Fan", factor: 10 },
      { trait: "Technophobe", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Technophobe", factor: 0 }],
    requiredAge: "child",
    expansion: "Into the Future",
  },
  {
    label: "Can't Stand Art",
    iconUrl: "/Trait_Cant_Stand_Art.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Can't Stand Art", factor: 10 },
      { trait: "Artistic", factor: 0.8 },
      { trait: "Easily Impressed", factor: 0.8 },
      { trait: "Savvy Sculptor", factor: 0.8 },
      { trait: "Avant Garde", factor: 0.8 },
    ],
    ownInfluence: [
      { trait: "Artistic", factor: 0 },
      { trait: "Easily Impressed", factor: 0 },
      { trait: "Savvy Sculptor", factor: 0 },
      { trait: "Avant Garde", factor: 0 },
    ],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Cat Person",
    iconUrl: "/Trait_Cat_Person.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Cat Person", factor: 10 },
      { trait: "Animal Lover", factor: 5 },
      { trait: "Dog Person", factor: 5 },
      { trait: "Equestrian", factor: 5 },
    ],
    ownInfluence: [
      { trait: "Animal Lover", factor: 0 },
      { trait: "Dog Person", factor: 0 },
      { trait: "Equestrian", factor: 0 },
    ],
    requiredAge: "child",
    expansion: "Pets",
  },
  {
    label: "Computer Whiz",
    iconUrl: "/Trait_Computer_Whiz.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Computer Whiz", factor: 10 },
      { trait: "Technophobe", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Technophobe", factor: 0 }],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Coward",
    iconUrl: "/Trait_Coward.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Coward", factor: 10 },
      { trait: "Brave", factor: 0.8 },
      { trait: "Daredevil", factor: 0.8 },
      { trait: "Natural Born Performer", factor: 0.8 },
      { trait: "Supernatural Fan", factor: 0.8 },
    ],
    ownInfluence: [
      { trait: "Brave", factor: 0 },
      { trait: "Daredevil", factor: 0 },
      { trait: "Natural Born Performer", factor: 0 },
      { trait: "Supernatural Fan", factor: 0 },
    ],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Daredevil",
    iconUrl: "/Trait_Daredevil.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Daredevil", factor: 10 },
      { trait: "Coward", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Coward", factor: 0 }],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Diva",
    iconUrl: "/Trait_Diva.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Diva", factor: 10 },
      { trait: "Charismatic", factor: 5 },
    ],
    ownInfluence: [],
    requiredAge: "child",
    expansion: "Showtime",
  },
  {
    label: "Dog Person",
    iconUrl: "/Trait_Dog_Person.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Dog Person", factor: 10 },
      { trait: "Animal Lover", factor: 5 },
      { trait: "Cat Person", factor: 5 },
      { trait: "Equestrian", factor: 5 },
    ],
    ownInfluence: [
      { trait: "Animal Lover", factor: 0 },
      { trait: "Cat Person", factor: 0 },
      { trait: "Equestrian", factor: 0 },
    ],
    requiredAge: "child",
    expansion: "Pets",
  },
  {
    label: "Eco-Friendly",
    iconUrl: "/Trait_Eco-Friendly.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Eco-Friendly", factor: 10 },
      { trait: "Hates the Outdoors", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Hates the Outdoors", factor: 0 }],
    requiredAge: "child",
    expansion: "Ambitions",
  },
  {
    label: "Equestrian",
    iconUrl: "/Trait_Equestrian.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Equestrian", factor: 10 },
      { trait: "Dog Person", factor: 5 },
      { trait: "Animal Lover", factor: 5 },
      { trait: "Cat Person", factor: 5 },
    ],
    ownInfluence: [
      { trait: "Dog Person", factor: 0 },
      { trait: "Animal Lover", factor: 0 },
      { trait: "Cat Person", factor: 0 },
    ],
    requiredAge: "child",
    expansion: "Pets",
  },
  {
    label: "Family-Oriented",
    iconUrl: "/Trait_Family-Oriented.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Family-Oriented", factor: 10 },
      { trait: "Nurturing", factor: 5 },
      { trait: "Dislikes Children", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Dislikes Children", factor: 0 }],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Frugal",
    iconUrl: "/Trait_Frugal.webp",
    weight: 100,
    parentInfluence: [{ trait: "Frugal", factor: 10 }],
    ownInfluence: [],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Good Sense of Humor",
    iconUrl: "/Trait_Good_Sense_of_Humor.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Good Sense of Humor", factor: 10 },
      { trait: "No Sense of Humor", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "No Sense of Humor", factor: 0 }],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Hot-Headed",
    iconUrl: "/Trait_Hot-Headed.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Hot-Headed", factor: 10 },
      { trait: "Grumpy", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Grumpy", factor: 0 }],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Hydrophobic",
    iconUrl: "/Trait_Hydrophobic.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Hydrophobic", factor: 10 },
      { trait: "Loves To Swim", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Loves To Swim", factor: 0 }],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Inappropriate",
    iconUrl: "/Trait_Inappropriate.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Inappropriate", factor: 10 },
      { trait: "Proper", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Proper", factor: 0 }],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Kleptomaniac",
    iconUrl: "/Trait_Kleptomaniac.webp",
    weight: 100,
    parentInfluence: [{ trait: "Kleptomaniac", factor: 10 }, ,],
    ownInfluence: [],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Loser",
    iconUrl: "/Trait_Loser.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Loser", factor: 10 },
      { trait: "Brave", factor: 0.8 },
      { trait: "Charismatic", factor: 0.8 },
    ],
    ownInfluence: [
      { trait: "Brave", factor: 0 },
      { trait: "Charismatic", factor: 0 },
    ],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Loves To Swim",
    iconUrl: "/Trait_Loves_To_Swim.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Loves To Swim", factor: 10 },
      { trait: "Hydrophobic", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Hydrophobic", factor: 0 }],
    requiredAge: "child",
    expansion: "Island Paradise",
  },
  {
    label: "Lucky",
    iconUrl: "/Trait_Lucky.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Lucky", factor: 10 },
      { trait: "Unlucky", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Unlucky", factor: 0 }],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Mean Spirited",
    iconUrl: "/Trait_Mean_Spirited.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Mean Spirited", factor: 10 },
      { trait: "Evil", factor: 5 },
      { trait: "Friendly", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Friendly", factor: 0 }],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Mooch",
    iconUrl: "/Trait_Mooch.webp",
    weight: 100,
    parentInfluence: [{ trait: "Mooch", factor: 10 }],
    ownInfluence: [],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Neat",
    iconUrl: "/Trait_Neat.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Neat", factor: 10 },
      { trait: "Slob", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Slob", factor: 0 }],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Never Nude",
    iconUrl: "/Trait_Never_Nude.webp",
    weight: 100,
    parentInfluence: [{ trait: "Never Nude", factor: 10 }],
    ownInfluence: [],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Night Owl",
    iconUrl: "/Trait_Night_Owl.webp",
    weight: 100,
    parentInfluence: [{ trait: "Night Owl", factor: 10 }],
    ownInfluence: [],
    requiredAge: "child",
    expansion: "Supernatural",
  },
  {
    label: "No Sense of Humor",
    iconUrl: "/Trait_No_Sense_of_Humor.webp",
    weight: 100,
    parentInfluence: [
      { trait: "No Sense of Humor", factor: 10 },
      { trait: "Good Sense of Humor", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Good Sense of Humor", factor: 0 }],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Over-Emotional",
    iconUrl: "/Trait_Over-Emotional.webp",
    weight: 100,
    parentInfluence: [{ trait: "Over-Emotional", factor: 10 }],
    ownInfluence: [],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Party Animal",
    iconUrl: "/Trait_Party_Animal.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Party Animal", factor: 10 },
      { trait: "Loner", factor: 0.8 },
      { trait: "Shy", factor: 0.8 },
    ],
    ownInfluence: [
      { trait: "Loner", factor: 0 },
      { trait: "Shy", factor: 0 },
    ],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Perfectionist",
    iconUrl: "/Trait_Perfectionist.webp",
    weight: 100,
    parentInfluence: [{ trait: "Perfectionist", factor: 10 }],
    ownInfluence: [],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Photographer's Eye",
    iconUrl: "/Trait_Photographers_Eye.webp",
    weight: 100,
    parentInfluence: [{ trait: "Photographer's Eye", factor: 10 }],
    ownInfluence: [],
    requiredAge: "child",
    expansion: "World Adventures",
  },
  {
    label: "Rebellious",
    iconUrl: "/Trait_Rebellious.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Rebellious", factor: 10 },
      { trait: "Schmoozer", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Schmoozer", factor: 0 }],
    requiredAge: "child",
    expansion: "Generations",
  },
  {
    label: "Shy",
    iconUrl: "/Trait_Shy.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Shy", factor: 10 },
      { trait: "Flirty", factor: 0.8 },
      { trait: "Party Animal", factor: 0.8 },
      { trait: "Social Butterfly", factor: 0.8 },
    ],
    ownInfluence: [
      ,
      { trait: "Flirty", factor: 0 },
      { trait: "Party Animal", factor: 0 },
      { trait: "Social Butterfly", factor: 0 },
    ],
    requiredAge: "child",
    expansion: "Late Night",
  },
  {
    label: "Snob",
    iconUrl: "/Trait_Snob.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Snob", factor: 10 },
      { trait: "Easily Impressed", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Easily Impressed", factor: 0 }],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Star Quality",
    iconUrl: "/Trait_Star_Quality.webp",
    weight: 100,
    parentInfluence: [{ trait: "Star Quality", factor: 10 }],
    ownInfluence: [],
    requiredAge: "child",
    expansion: "Late Night",
  },
  {
    label: "Supernatural Fan",
    iconUrl: "/Trait_Supernatural_Fan.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Supernatural Fan", factor: 10 },
      { trait: "Supernatural Skeptic", factor: 0.8 },
      { trait: "Coward", factor: 0.8 },
    ],
    ownInfluence: [
      { trait: "Supernatural Skeptic", factor: 0 },
      { trait: "Coward", factor: 0 },
    ],
    requiredAge: "child",
    expansion: "Supernatural",
  },
  {
    label: "Technophobe",
    iconUrl: "/Trait_Technophobe.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Technophobe", factor: 10 },
      { trait: "Computer Whiz", factor: 0.8 },
      { trait: "Bot Fan", factor: 0.8 },
      { trait: "Couch Potato", factor: 0.8 },
    ],
    ownInfluence: [
      { trait: "Computer Whiz", factor: 0 },
      { trait: "Bot Fan", factor: 0 },
      { trait: "Couch Potato", factor: 0 },
    ],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Unlucky",
    iconUrl: "/Trait_Unlucky.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Unlucky", factor: 10 },
      { trait: "Lucky", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Lucky", factor: 0 }],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Unstable",
    iconUrl: "/Trait_Unstable.webp",
    weight: 100,
    parentInfluence: [{ trait: "Unstable", factor: 10 }],
    ownInfluence: [],
    requiredAge: "child",
    expansion: "Into the Future",
  },
  {
    label: "Vegetarian",
    iconUrl: "/Trait_Vegetarian.webp",
    weight: 100,
    parentInfluence: [{ trait: "Vegetarian", factor: 10 }],
    ownInfluence: [],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Vehicle Enthusiast",
    iconUrl: "/Trait_Vehicle_Enthusiast.webp",
    weight: 100,
    parentInfluence: [{ trait: "Vehicle Enthusiast", factor: 10 }],
    ownInfluence: [],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Workaholic",
    iconUrl: "/Trait_Workaholic.webp",
    weight: 100,
    parentInfluence: [{ trait: "Workaholic", factor: 10 }],
    ownInfluence: [],
    requiredAge: "child",
    expansion: "Base Game",
  },
  {
    label: "Avant Garde",
    iconUrl: "/Trait_Avant_Garde.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Avant Garde", factor: 10 },
      { trait: "Can't Stand Art", factor: 0.8 },
      { trait: "Easily Impressed", factor: 0.8 },
    ],
    ownInfluence: [
      { trait: "Can't Stand Art", factor: 0 },
      { trait: "Easily Impressed", factor: 0 },
    ],
    requiredAge: "teen",
    expansion: "University Life",
  },
  {
    label: "Born Salesperson",
    iconUrl: "/Trait_Born_Salesperson.webp",
    weight: 100,
    parentInfluence: [{ trait: "Born Salesperson", factor: 10 }],
    ownInfluence: [],
    requiredAge: "teen",
    expansion: "Ambitions",
  },
  {
    label: "Brooding",
    iconUrl: "/Trait_Brooding.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Brooding", factor: 10 },
      { trait: "Excitable", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Excitable", factor: 0 }],
    requiredAge: "teen",
    expansion: "Supernatural",
  },
  {
    label: "Charismatic",
    iconUrl: "/Trait_Charismatic.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Charismatic", factor: 10 },
      { trait: "Loser", factor: 0.8 },
      { trait: "Socially Awkward", factor: 0.8 },
    ],
    ownInfluence: [
      { trait: "Loser", factor: 0 },
      { trait: "Socially Awkward", factor: 0.8 },
    ],
    requiredAge: "teen",
    expansion: "Base Game",
  },
  {
    label: "Childish",
    iconUrl: "/Trait_Childish.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Childish", factor: 10 },
      { trait: "Dislikes Children", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Dislikes Children", factor: 0 }],
    requiredAge: "teen",
    expansion: "Base Game",
  },
  {
    label: "Commitment Issues",
    iconUrl: "/Trait_Commitment_Issues.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Commitment Issues", factor: 10 },
      { trait: "Hopeless Romantic", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Hopeless Romantic", factor: 0 }],
    requiredAge: "teen",
    expansion: "Base Game",
  },
  {
    label: "Dislikes Children",
    iconUrl: "/Trait_Dislikes_Children.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Dislikes Children", factor: 10 },
      { trait: "Family-Oriented", factor: 0.8 },
      { trait: "Childish", factor: 0.8 },
      { trait: "Nurturing", factor: 0.8 },
    ],
    ownInfluence: [
      { trait: "Family-Oriented", factor: 0 },
      { trait: "Childish", factor: 0 },
      { trait: "Nurturing", factor: 0 },
    ],
    requiredAge: "teen",
    expansion: "Base Game",
  },
  {
    label: "Dramatic",
    iconUrl: "/Trait_Dramatic.webp",
    weight: 100,
    parentInfluence: [{ trait: "Dramatic", factor: 10 }],
    ownInfluence: [],
    requiredAge: "teen",
    expansion: "Ambitions",
  },
  {
    label: "Flirty",
    iconUrl: "/Trait_Flirty.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Flirty", factor: 10 },
      { trait: "Shy", factor: 0.8 },
      { trait: "Unflirty", factor: 0.8 },
    ],
    ownInfluence: [
      { trait: "Unflirty", factor: 0 },
      { trait: "Shy", factor: 0 },
    ],
    requiredAge: "teen",
    expansion: "Base Game",
  },
  {
    label: "Gatherer",
    iconUrl: "/Trait_Gatherer.webp",
    weight: 100,
    parentInfluence: [{ trait: "Gatherer", factor: 10 }],
    ownInfluence: [],
    requiredAge: "teen",
    expansion: "Supernatural",
  },
  {
    label: "Great Kisser",
    iconUrl: "/Trait_Great_Kisser.webp",
    weight: 100,
    parentInfluence: [{ trait: "Great Kisser", factor: 10 }],
    ownInfluence: [],
    requiredAge: "teen",
    expansion: "Base Game",
  },
  {
    label: "Green Thumb",
    iconUrl: "/Trait_Green_Thumb.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Green Thumb", factor: 10 },
      { trait: "Hates the Outdoors", factor: 0.8 },
    ],
    ownInfluence: [],
    requiredAge: "teen",
    expansion: "Base Game",
  },
  {
    label: "Handy",
    iconUrl: "/Trait_Handy.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Handy", factor: 10 },
      { trait: "Clumsy", factor: 0.8 },
    ],
    ownInfluence: [],
    requiredAge: "teen",
    expansion: "Base Game",
  },
  {
    label: "Hopeless Romantic",
    iconUrl: "/Trait_Hopeless_Romantic.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Hopeless Romantic", factor: 10 },
      { trait: "Commitment Issues", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Commitment Issues", factor: 0 }],
    requiredAge: "teen",
    expansion: "Base Game",
  },
  {
    label: "Irresistible",
    iconUrl: "/Trait_Irresistible.webp",
    weight: 100,
    parentInfluence: [{ trait: "Irresistible", factor: 10 }],
    ownInfluence: [],
    requiredAge: "teen",
    expansion: "University Life",
  },
  {
    label: "Natural Born Performer",
    iconUrl: "/Trait_Natural_Born_Performer.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Natural Born Performer", factor: 10 },
      { trait: "Shy", factor: 0.8 },
      { trait: "Coward", factor: 0.8 },
      { trait: "Clumsy", factor: 0.8 },
    ],
    ownInfluence: [
      { trait: "Coward", factor: 0 },
      { trait: "Clumsy", factor: 0 },
    ],
    requiredAge: "teen",
    expansion: "Showtime",
  },
  {
    label: "Natural Cook",
    iconUrl: "/Trait_Natural_Cook.webp",
    weight: 100,
    parentInfluence: [{ trait: "Natural Cook", factor: 10 }],
    ownInfluence: [],
    requiredAge: "teen",
    expansion: "Base Game",
  },
  {
    label: "Nurturing",
    iconUrl: "/Trait_Nurturing.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Nurturing", factor: 10 },
      { trait: "Dislikes Children", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Dislikes Children", factor: 0 }],
    requiredAge: "teen",
    expansion: "Generations",
  },
  {
    label: "Proper",
    iconUrl: "/Trait_Proper.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Proper", factor: 10 },
      { trait: "Inappropriate", factor: 0.8 },
      { trait: "Slob", factor: 0.8 },
    ],
    ownInfluence: [
      { trait: "Inappropriate", factor: 0 },
      { trait: "Slob", factor: 0 },
    ],
    requiredAge: "teen",
    expansion: "Supernatural",
  },
  {
    label: "Savvy Sculptor",
    iconUrl: "/Trait_Savvy_Sculptor.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Savvy Sculptor", factor: 10 },
      { trait: "Can't Stand Art", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Can't Stand Art", factor: 0 }],
    requiredAge: "teen",
    expansion: "Ambitions",
  },
  {
    label: "Schmoozer",
    iconUrl: "/Trait_Schmoozer.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Schmoozer", factor: 10 },
      { trait: "Rebellious", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Rebellious", factor: 0 }],
    requiredAge: "teen",
    expansion: "Base Game",
  },
  {
    label: "Social Butterfly",
    iconUrl: "/Trait_Social_Butterfly.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Social Butterfly", factor: 10 },
      { trait: "Shy", factor: 0.8 },
      { trait: "Loner", factor: 0.8 },
    ],
    ownInfluence: [
      { trait: "Shy", factor: 0 },
      { trait: "Loner", factor: 0 },
    ],
    requiredAge: "teen",
    expansion: "Showtime",
  },
  {
    label: "Socially Awkward",
    iconUrl: "/Trait_Socially_Awkward.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Socially Awkward", factor: 10 },
      { trait: "Charismatic", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Charismatic", factor: 0 }],
    requiredAge: "teen",
    expansion: "University Life",
  },
  {
    label: "Supernatural Skeptic",
    iconUrl: "/Trait_Supernatural_Skeptic.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Supernatural Skeptic", factor: 10 },
      { trait: "Supernatural Fan", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Supernatural Fan", factor: 0 }],
    requiredAge: "teen",
    expansion: "Supernatural",
  },
  {
    label: "Unflirty",
    iconUrl: "/Trait_Unflirty.webp",
    weight: 100,
    parentInfluence: [
      { trait: "Unflirty", factor: 10 },
      { trait: "Flirty", factor: 0.8 },
    ],
    ownInfluence: [{ trait: "Flirty", factor: 0 }],
    requiredAge: "teen",
    expansion: "Base Game",
  },
];
